### ISSUE TITLE
Number of computed frames from visibility matrix

### ISSUE THREAD

**Issue by adrianSRoman** [imagingofthings/DeepWave#2]
https://github.com/imagingofthings/DeepWave/blob/6bb46f330d9745d4a4871d412cd4f4730bbbcfdd/datasets/FRIDA/extract_dataset.py#L136

Hi all, 

Thanks for sharing this awesome work with us.

From the line reference pasted above, I was wondering why we make `N_sti_per_stationary_block = 9` if ideally we want to have 10 frames per second. I took a closer look at this and it seems to be causing the number of 100msec frames being shorter than the actual length of the audio tracks we use. Removing the `+1` allows us to have matching 100 sec frames with the track duration.

**Comment by SepandKashani** [comment]
Hi Adrian,

`form_visibility()` was originally written for another context (radio-astronomy) where `T_sti` and `T_stationarity` may not be multiples of each other. In this case we need to do some rounding, hence the `int() + 1`.

Moreover in the radio-astronomy context, it is common to assume stationarity over 8-10 STIs, hence the factor 8 in https://github.com/imagingofthings/DeepWave/blob/6bb46f330d9745d4a4871d412cd4f4730bbbcfdd/datasets/FRIDA/extract_dataset.py#L170

Of course one can set `T_sti = 10e-3`,  `T_stationarity = 10 * T_sti`, and get rid of the rounding code in `form_visibility()` to obtain 10 FPS.

Sorry for the confusing comment in the code.

**Comment by adrianSRoman** [comment]
Thanks for the prompt response and clear explanation — makes sense!
